#!/usr/bin/env python

# Echo client program
import socket

HOST = 'localhost'    # The remote host
PORT = 11111          # The same port as used by the server

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))

while 1:
    raw_input("Press ENTER to send 'Hello, world': ")
    s.send('Hello, world')
    print 'Message Sent To Server'

    data = s.recv(1024)
#s.close()

    print ('Received From Server:', repr(data))
