#!/usr/bin/env python

# Echo server program
import socket

HOST = ''                 # Symbolic name meaning the local host
PORT = 11111              # Arbitrary non-privileged port

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind((HOST, PORT))
s.listen(1)

print ("Server Started")

conn, addr = s.accept()
print ("conn = ", conn)
print ('Connected by', addr)

while 1:
    data = conn.recv(1024)
    if data:
        print ("Data Received:", data)
        conn.send(data)

#conn.close()

